DROP TABLE `zt_group`, `zt_groupPriv`, `zt_userGroup`;

CREATE TABLE `zt_product` (
    `id` MEDIUMINT( 8 ) UNSIGNED NOT NULL AUTO_INCREMENT ,
    `name` VARCHAR( 90 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
    `order` TINYINT( 3 ) UNSIGNED NOT NULL ,
    PRIMARY KEY ( `id` ) 
  ) ENGINE = MYISAM ;

ALTER TABLE `zt_product` ADD `status` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `zt_category` ADD `product` MEDIUMINT( 8 ) NOT NULL;
ALTER TABLE `zt_faq` ADD `product` MEDIUMINT( 8 ) UNSIGNED NOT NULL AFTER `id`;
DROP TABLE `zt_config`;
CREATE TABLE `zt_config` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `openSync` BOOL NOT NULL ,
  `key` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
  `ip` VARCHAR( 15 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL 
) ENGINE = MYISAM;
INSERT INTO `zt_config` ( `id` , `openSync` , `key` , `ip` ) VALUES ( NULL , '0', '', '');
ALTER TABLE `zt_request` ADD `product` MEDIUMINT( 8 ) UNSIGNED NOT NULL AFTER `id`;
ALTER TABLE `zt_request` ADD `isForwarded` ENUM( '1', '0' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' AFTER `status`;

CREATE TABLE `zt_serviceTime` (
  `id` MEDIUMINT( 8 ) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `user` MEDIUMINT( 8 ) NOT NULL ,
  `product` MEDIUMINT( 8 ) NOT NULL ,
  `serviceTime` DATE NOT NULL ,
  `deleted` ENUM( '0', '1' ) NOT NULL DEFAULT '0',
  PRIMARY KEY ( `id` )
) ENGINE = MYISAM; 
ALTER TABLE `zt_serviceTime` CHANGE `deleted` `deleted` ENUM( '0', '1' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' ;
ALTER TABLE `zt_user` DROP `serviceTime`;
ALTER TABLE `zt_request` DROP `isForwarded`;

-- DROP TABLE IF EXISTS `zt_group`;
CREATE TABLE IF NOT EXISTS `zt_group` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `name` char(30) NOT NULL,
  `desc` char(255) NOT NULL default '',
  PRIMARY KEY  (`id`)
  ) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
  -- DROP TABLE IF EXISTS `zt_groupPriv`;
CREATE TABLE IF NOT EXISTS `zt_groupPriv` (
  `group` mediumint(8) unsigned NOT NULL default '0',
  `module` char(30) NOT NULL default '',
  `method` char(30) NOT NULL default '',
  UNIQUE KEY `group` (`group`,`module`,`method`)
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `zt_group` (`id`, `name`, `desc`) VALUES
(1, 'admin',    '系统管理员'),
(2, 'manager',  '客服经理'),
(3, 'support',  '技术支持'),
(4, 'servicer', '客服'),
(5, 'customer', '客户');

INSERT INTO `zt_groupPriv` (`group`, `module`, `method`) VALUES
(1, 'admin', 'footer'),
(1, 'admin', 'index'),
(1, 'admin', 'leftMenu'),
(1, 'admin', 'topMenu'),
(1, 'api', 'getModel'),
(1, 'category', 'delete'),
(1, 'category', 'manage'),
(1, 'category', 'updateOrder'),
(1, 'faq', 'create'),
(1, 'faq', 'delete'),
(1, 'faq', 'edit'),
(1, 'faq', 'manage'),
(1, 'file', 'ajaxUpload'),
(1, 'file', 'delete'),
(1, 'file', 'download'),
(1, 'group', 'browse'),
(1, 'group', 'managePriv'),
(1, 'misc', 'ping'),
(1, 'product', 'manage'),
(1, 'product', 'stop'),
(1, 'product', 'updateorder'),
(1, 'request', 'assignedTo'),
(1, 'request', 'browse'),
(1, 'request', 'close'),
(1, 'request', 'comment'),
(1, 'request', 'reply'),
(1, 'request', 'transfer'),
(1, 'request', 'view'),
(1, 'search', 'buildForm'),
(1, 'search', 'buildQuery'),
(1, 'search', 'deleteQuery'),
(1, 'search', 'saveQuery'),
(1, 'search', 'select'),
(1, 'setting', 'syncConfig'),
(1, 'user', 'addProductService'),
(1, 'user', 'ajaxGetUser'),
(1, 'user', 'allow'),
(1, 'user', 'browse'),
(1, 'user', 'create'),
(1, 'user', 'delete'),
(1, 'user', 'edit'),
(1, 'user', 'extendProductService'),
(1, 'user', 'forbid'),
(1, 'user', 'manageProductService'),
(1, 'user', 'profile'),
(1, 'user', 'view'),
(2, 'admin', 'footer'),
(2, 'admin', 'index'),
(2, 'admin', 'leftMenu'),
(2, 'admin', 'topMenu'),
(2, 'api', 'getModel'),
(2, 'category', 'delete'),
(2, 'category', 'manage'),
(2, 'category', 'updateOrder'),
(2, 'faq', 'create'),
(2, 'faq', 'delete'),
(2, 'faq', 'edit'),
(2, 'faq', 'manage'),
(2, 'file', 'ajaxUpload'),
(2, 'file', 'delete'),
(2, 'file', 'download'),
(2, 'group', 'browse'),
(2, 'misc', 'ping'),
(2, 'product', 'manage'),
(2, 'product', 'stop'),
(2, 'product', 'updateorder'),
(2, 'request', 'assignedTo'),
(2, 'request', 'browse'),
(2, 'request', 'close'),
(2, 'request', 'comment'),
(2, 'request', 'reply'),
(2, 'request', 'transfer'),
(2, 'request', 'view'),
(2, 'search', 'buildForm'),
(2, 'search', 'buildQuery'),
(2, 'search', 'deleteQuery'),
(2, 'search', 'saveQuery'),
(2, 'search', 'select'),
(2, 'user', 'addProductService'),
(2, 'user', 'ajaxGetUser'),
(2, 'user', 'allow'),
(2, 'user', 'browse'),
(2, 'user', 'create'),
(2, 'user', 'delete'),
(2, 'user', 'edit'),
(2, 'user', 'extendProductService'),
(2, 'user', 'forbid'),
(2, 'user', 'manageProductService'),
(2, 'user', 'profile'),
(2, 'user', 'view'),
(3, 'admin', 'footer'),
(3, 'admin', 'index'),
(3, 'admin', 'leftMenu'),
(3, 'admin', 'topMenu'),
(3, 'faq', 'create'),
(3, 'faq', 'delete'),
(3, 'faq', 'edit'),
(3, 'faq', 'manage'),
(3, 'file', 'ajaxUpload'),
(3, 'file', 'delete'),
(3, 'file', 'download'),
(3, 'misc', 'ping'),
(3, 'request', 'assignedTo'),
(3, 'request', 'browse'),
(3, 'request', 'close'),
(3, 'request', 'reply'),
(3, 'request', 'transfer'),
(3, 'request', 'view'),
(3, 'search', 'buildForm'),
(3, 'search', 'buildQuery'),
(3, 'search', 'deleteQuery'),
(3, 'search', 'saveQuery'),
(3, 'search', 'select'),
(3, 'user', 'browse'),
(3, 'user', 'edit'),
(3, 'user', 'profile'),
(3, 'user', 'view'),
(4, 'admin', 'footer'),
(4, 'admin', 'index'),
(4, 'admin', 'leftMenu'),
(4, 'admin', 'topMenu'),
(4, 'faq', 'create'),
(4, 'faq', 'edit'),
(4, 'faq', 'manage'),
(4, 'file', 'ajaxUpload'),
(4, 'file', 'delete'),
(4, 'file', 'download'),
(4, 'misc', 'ping'),
(4, 'request', 'assignedTo'),
(4, 'request', 'browse'),
(4, 'request', 'close'),
(4, 'request', 'reply'),
(4, 'request', 'transfer'),
(4, 'request', 'view'),
(4, 'search', 'buildForm'),
(4, 'search', 'buildQuery'),
(4, 'search', 'deleteQuery'),
(4, 'search', 'saveQuery'),
(4, 'search', 'select'),
(4, 'user', 'ajaxGetUser'),
(4, 'user', 'browse'),
(4, 'user', 'edit'),
(4, 'user', 'profile'),
(4, 'user', 'view'),
(5, 'file', 'ajaxUpload'),
(5, 'file', 'delete'),
(5, 'file', 'download'),
(5, 'misc', 'ping'),
(5, 'request', 'browse'),
(5, 'request', 'doubt'),
(5, 'request', 'edit'),
(5, 'request', 'request'),
(5, 'request', 'valuate'),
(5, 'request', 'view'),
(5, 'user', 'check'),
(5, 'user', 'edit'),
(5, 'user', 'myService'),
(5, 'user', 'profile'),
(5, 'user', 'reset');
(5, 'user', 'index');
(5, 'user', 'modifyPassword');

